### ISSUE TITLE
incompatibility with menu mods

### ISSUE THREAD

**Issue by biscqit** [DeDiamondPro/Resourcify#10]
**Technical Information**
Resourcify version: 1.1.0
Minecraft version:1.20x
Other mods (if relevant):
reese's sodium option and puzzle
**Describe the bug**
after opening the menus' options and clicking anywhere the client crashes
**Expected behavior**
the menus to function properly without crashing the client

also thanks for da cool mod, really appreciate all the time you put into dis <3

**Comment by CoolGuyGit** [comment]
Hey, I have a similar issue with the mod when I'm using it in my modpack, this is the crash log. 

[crash.log](https://github.com/DeDiamondPro/Resourcify/files/12206025/crash.log)

**Comment by jbrown1597** [comment]
Having the same issue. I also have both of these mods installed.

Log file here: https://drive.google.com/file/d/1nyMz0UktOMa-Xj1_WOZvA-j9KKF1Hy34/view?usp=sharing

**Comment by jbrown1597** [comment]
> I am unable to reproduce this crash. Could you send me the crash log of this crash? (Can be found in .minecraft/crash-reports). In addition to this could you tell me exactly which menu you opened where the crash occured?

Having the same issue. I also have both of these mods installed.

Log file here: https://drive.google.com/file/d/1nyMz0UktOMa-Xj1_WOZvA-j9KKF1Hy34/view?usp=sharing

**Comment by DeDiamondPro** [comment]
> Having the same issue. I also have both of these mods installed. (1.20.1 Fabric)
> 
> 
> 
> Log file here: https://www.mediafire.com/file/1qp8bgdmxftrgw0/crash-2023-07-30_15.09.06-client.txt/file

I believe your issue is related to #9 and has nothing to do with the 2 mods outlined in this issue

**Comment by DeDiamondPro** [comment]
Closing because no further logs were provided
