### ISSUE TITLE
Oculus support for shaderpack browser

### ISSUE THREAD

**Issue by JunkiEDM** [DeDiamondPro/Resourcify#12]
It would be nice if the shaderpack browser was accessible using [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus), a fork of Iris for FML, since many modpacks don't support Optifine or otherwise opt to use the Rubidium "family" of mods since Optifine isn't on curse/modrinth.
<details><summary>Screenshot</summary>

![image](https://github.com/DeDiamondPro/Resourcify/assets/8350274/e9b3ddb9-3582-4f3c-ab21-b46d32905df5)
</details>

**Comment by DeDiamondPro** [comment]
Support was added in commit 150e314f0221ccaa39af4909d9cd65562010e3b9 and will be released with the next release
