### ISSUE TITLE
Make the GUI scale be controllable

### ISSUE THREAD

**Issue by PowerRubik** [DeDiamondPro/Resourcify#13]
**Describe the solution you'd like**
Make the gui scale be controllable by a slider in the video settings menu or automatically the same GUI scale of the game.

**Comment by DeDiamondPro** [comment]
Hi,
The GUI should follow the game's GUI scale unless the scaled width is too small to properly display the GUI, then it will go to a lower GUI scale. Without this behavior the GUI has trouble displaying in a manor that is easy to use.
If this is not the behavior you are experiencing please tell me what GUI scale and resolution you use so I can look into it

**Comment by DeDiamondPro** [comment]
Closing since no answer was provided
