### ISSUE TITLE
mod spamming errors

### ISSUE THREAD

**Issue by Thunderrock424242** [DeDiamondPro/Resourcify#16]
**Technical Information**
Resourcify version: 1.1.1
Minecraft version: 1.20.1
Other mods (if relevant):

**Describe the bug**
its spaming errors https://mclo.gs/FJkZ7Ir
**Expected behavior**
to not spam erorrs
**Steps to reproduce**
Describe the steps to reproduce the issue

**Additional information**
Anything else that might be useful to fix this issue, for example a crash log.

**Comment by DeDiamondPro** [comment]
After looking into it I have no idea how to solve this, but it doesn't seem to effect to mods functionality which is good
