### ISSUE TITLE
Incompatibility w another sound mod  [Log Provided]

### ISSUE THREAD

**Issue by jbrown1597** [DeDiamondPro/Resourcify#18]
Resourcify version: 1.20.x-fabric-1.1.0 (*FIXED VERSION)
Minecraft version: 1.20.1 Fabric

Crashes upon touching any of the vanilla sound sliders.
No longer crashes upon removing Resourcify.

P.S - Thanks for fixing the previous conflictions. You're a real one <3

Potential suspects: Sound Controller (https://modrinth.com/mod/sound-controller)

[new crash.txt](https://github.com/DeDiamondPro/Resourcify/files/12342157/new.crash.txt)

**Comment by DeDiamondPro** [comment]
Hi,
This issue should already be fixed in 1.1.2 https://modrinth.com/mod/resourcify/versions

**Comment by jbrown1597** [comment]
LOL. You're too good. Thanks for everything you do.
