### ISSUE TITLE
The game crashes when I try to open the resource pack browser menu!

### ISSUE THREAD

**Issue by HenrikoMagnifico** [DeDiamondPro/Resourcify#27]
**Technical Information**
Resourcify version: Resourcify (1.12.2-forge)-1.3.1
Minecraft version: 1.12.2
Other mods (if relevant):
All mods in [Yao Pack 3](https://www.technicpack.net/modpack/yao-pack-3.1954207)

**Describe the bug**
The game crashes when I press the button.

**Expected behavior**
For the game not to crash

**Steps to reproduce**
Press the button to open the resource pack browser menu

**Additional information**
Crash log: https://pastebin.com/D0WpVNpp

**Comment by Not-Zero-Blank** [comment]
Hi @DeDiamondPro
I can confirm this Solved the Issue
Thanks!
