### ISSUE TITLE
Crash on Search Entry | Fabric for 1.20.5

### ISSUE THREAD

**Issue by Oxeus** [DeDiamondPro/Resourcify#30]
**Technical Information**
Resourcify version: 1.3.4
Minecraft version: 1.20.5 with fabric laoder 0.15.10
Other mods (if relevant): Appleskin, Betterstats, capes, cloth config, controlling, entity culling, Fabric API, fabric Language Kotlin, Falling Leaves, Iris, Jade, JourneyMap, Not Enough Animations, Particle Rain, Reeses Sodium Options, resourcify, remove reloading screen, searchables, simple voice chat, sodium, sodium extra, sound physics remastered, spark, visuality, voicechat, waveycape, YetAnotherConfigLib, Zoomify.

**Describe the bug**
Browsing, Downloading, and Updating Packs are Fine, the bug occurs when attempting to search the list of packs for both Resource packs and shader packs. Upon entering text whether from keyboard or copy/paste the game crashes. 

**Expected behavior**
Game allows text to be entered, text is used to filter list of current packs. 

**Steps to reproduce**
Enter text into the search field. 

**Additional information**
latest.log attached
[latest.log](https://github.com/DeDiamondPro/Resourcify/files/15137121/latest.log)

I myself have looked through the source code and I think the culprit is this line of code:

@Override
public boolean isAllowedInChat(char c) {
    return ChatAllowedCharacters.isAllowedCharacter(c);
}

from the elementa library. It looks like mojang changed and or removed a method causing a java.lang.NoSuchMethodError: 'boolean net.minecraft.class_155.method_643(char)' error in the newest 1.20.5 update.

**Comment by DeDiamondPro** [comment]
Thank you for your report, I will start working on a fix

**Comment by DeDiamondPro** [comment]
Fix in 1.3.5, see https://modrinth.com/mod/resourcify/version/1.3.5
