### ISSUE TITLE
[Crash] Game Fails to Start with Latest Version of Resourcify

### ISSUE THREAD

**Issue by FocalFlare** [DeDiamondPro/Resourcify#32]
_Upon attempting to launch Minecraft after updating Resourcify to 1.3.6, the game immediately crashes without ever even starting up. Before finding this out by hard, I checked to see if this mod was the culprit and not any of the datapacks I downloaded and modified for my worlds._ 

_Here's what I tried doing to no avail:_ 
- [x] Undo all modification of my installed datapacks (and even disabled them).
- [x] Disable two of the most-recent mods I installed.

_I checked the log I attached for a line with "caused by" and the line I see with that has this:_
_`Caused by: java.lang.RuntimeException: Failed to parse spec`_
_I'm not really sure what that even means but it's coming from this version of Resourcify only. Without it, the crash doesn't happen._

_**Solutions for this crash might work for everyone who's having this same issue but are 100% not guaranteed to work for those with even a slightly different issue, so please open another issue if yours is any different. Regardless, I appreciate your input(s)!**_

### **Technical Information**
Resourcify version: 1.3.6
Minecraft version: 1.18.2
Other mods (if relevant): Other mods specified in log &
- Embeddium [0.3.14]
- Embeddium++ [1.2.1a] 
- Forge (Loader) [40.2.18]

**Describe the bug**
_TL;DR: Latest version of Resourcify crashes Minecraft upon launch, causing exit code **2**. Previous version v1.3.3 doesn't trigger this crash._

**Expected behavior**
The game starts up like normal.

**Steps to reproduce**
1. Download or update Resourcify to v1.3.6.
2. Try to launch the game with this version of the mod [ends with exit code of **2**].

**Additional information**
_I know this might be a case of mod incompatibility, but if needed, I can provide a ZIP file of my currently enabled mods via Google Drive if you want to try and reproduce this._

**Log(s)**
This log was copied from my launcher and pasted into a text editor for saving.
[Prism Log from Installing Resourcify 1.3.6.txt](https://github.com/DeDiamondPro/Resourcify/files/15196530/Prism.Log.from.Installing.Resourcify.1.3.6.txt)

**Comment by DeDiamondPro** [comment]
Thank you for the report! Looks like I misconfigured the allowed minecraft versions causing the mods.toml file to fail parsing, I'll get a fix out in a bit

**Comment by DeDiamondPro** [comment]
I delisted the affected versions (1.3.6 for forge 1.18.2 and 1.19.4) and published 1.3.6.1 with a fix for the affected versions, it is available on [modrinth](https://modrinth.com/mod/resourcify/version/1.3.6.1) right now, and will be available on curseforge once it passes review, which will probably not be until sunday or maybe even later, unfortunately.

**Comment by FocalFlare** [comment]
_Alright I'll test this version out._
