### ISSUE TITLE
Game freezes when interacting with resource pack page

### ISSUE THREAD

**Issue by nenamoree9** [DeDiamondPro/Resourcify#33]
**Technical Information**
Resourcify version: 1.3.1
Minecraft version: 1.20.2-1.20.4
Other mods (if relevant): Recursive Resources

Something happens when you click the links on the top of the resource pack's page.
Usually, it will take you to a different page when you click those links but however, it just freezes instead.

So basically, you click the resource pack you want and then click the links and then it will freeze.

Exit code: -805306369

**Comment by DeDiamondPro** [comment]
Closing due to lack of response, if you are still having this issue please reopen this issue with the additional information requested.
