### ISSUE TITLE
Background breaks with Essential [1.20.6]

### ISSUE THREAD

**Issue by BluebirdYT** [DeDiamondPro/Resourcify#34]
**Technical Information**
Resourcify version: 1.3.6
Minecraft version: 1.20.6
Other mods (if relevant):
[Essential](https://modrinth.com/mod/essential)

**Describe the bug**
![image](https://github.com/DeDiamondPro/Resourcify/assets/76973207/b5c20e5b-d9cc-4ba7-b164-26ace9785724)

**Expected behavior**
![image](https://github.com/DeDiamondPro/Resourcify/assets/76973207/daa5232a-470b-4c30-bcdf-4e3b293d2fb3)

**Steps to reproduce**
Describe the steps to reproduce the issue
1. Open 1.20.6 with both Essential and Resourcify (And Resourcify's dependencies)
2. Open the resourcepack menu
3. Open the search for resourcepacks or the update resourcepacks menu with the button

**Additional information**
It may be on their end or your end so I don't know where to report this to.

**Comment by DeDiamondPro** [comment]
Thank you for the report, a fix is already implemented for the next version but it isn’t published yet

**Comment by DeDiamondPro** [comment]
A fix has been published in 1.4.0+beta.1: https://modrinth.com/mod/resourcify/versions
