### ISSUE TITLE
it doesnt open

### ISSUE THREAD

**Issue by lilmarksio** [DeDiamondPro/Resourcify#35]
**Technical Information**
Resourcify version:1.4.0+beta1
Minecraft version:1.20.4
Other mods (if relevant):

**Describe the bug
im clickin the plus button and it doesnt open
**Expected behavior**
opening menu idk

**Steps to reproduce**
go to options and then resource packs and then click the plus button idk
**Additional information**
Anything else that might be useful to fix this issue, for example a crash log.

**Comment by DeDiamondPro** [comment]
Hi, I am unfortunately unable to reproduce this issue, could you please provide me with your `latest.log` after you have attempted to press the plus button, and could you additionally please give me a list of other mods you are using so I can investigate if this might be a mod incompatibility.

**Comment by DeDiamondPro** [comment]
Closing due to lack of response, if you are still having this issue please reopen this issue with the additional information requested.
