### ISSUE TITLE
Click button crash

### ISSUE THREAD

**Issue by al-wei** [DeDiamondPro/Resourcify#38]
**Technical Information**
Resourcify version:Resourcify (1.12.2-forge)-1.4.0
Minecraft version:1.12.2
Other mods (if relevant):

**Describe the bug**
Click button crash
All Resourcify buttons

**Expected behavior**

**Steps to reproduce**
Describe the steps to reproduce the issue
Click button
![image](https://github.com/DeDiamondPro/Resourcify/assets/145486869/0bfaf2a9-9f95-4b99-9979-42e65ba01c5f)

**Additional information**
Anything else that might be useful to fix this issue, for example a crash log.
https://mclo.gs/WBPuZjm

**Comment by DeDiamondPro** [comment]
Hi, this is likely because another mod is including an older kotlin version than Resourcify, could you try renaming the Resourcify jar file to start with a `!` (for example `!resourcify.jar`) so forge loads Resourcify first, and hence loads the newer kotlin version instead of the old one.

**Comment by al-wei** [comment]
> Hi, this is likely because another mod is including an older kotlin version than Resourcify, could you try renaming the Resourcify jar file to start with a (for example ) so forge loads Resourcify first, and hence loads the newer kotlin version instead of the old one.`!``!resourcify.jar`

But it stopped updating,
What am I supposed to do,
Or do you fix it?

**Comment by al-wei** [comment]
> Hi, this is likely because another mod is including an older kotlin version than Resourcify, could you try renaming the Resourcify jar file to start with a (for example ) so forge loads Resourcify first, and hence loads the newer kotlin version instead of the old one.`!``!resourcify.jar`

To no use, I deleted kotlin in librarianlib-1.12.2-4.22 and still crashed when I clicked the button.
https://mclo.gs/gIWOWic

**Comment by al-wei** [comment]
Shadowfacts' Forgelin > Forgelin-Continuous

librarianlib-1.12.2-4.22 > librarianlib-1.12.2-4.19.2

This will solve the problem.

**Comment by al-wei** [comment]
> Shadowfacts' Forgelin > Forgelin-Continuous
> 
> librarianlib-1.12.2-4.22 > librarianlib-1.12.2-4.19.2
> 
> This will solve the problem.

You can write this scheme to the home page.
