### ISSUE TITLE
[Bug] Weird bug with the mod

### ISSUE THREAD

**Issue by Anonyku05** [DeDiamondPro/Resourcify#39]
**Technical Information**
Resourcify version: 1.4.0
Minecraft version: 1.20.4
Other mods (if relevant):

**Describe the bug**
Basically, the mod make the game go weird when cheking for updates, it seem to "corrupt" the game without actually corrupting it, check the video below:

https://github.com/DeDiamondPro/Resourcify/assets/48128391/f2809d00-14a5-4142-bf43-860408c1631c

**Expected behavior**
Must go back to ressource pack menu without any other issue.

**Steps to reproduce**
1- Go in a singleplayer world
2- Check for update then close

**Additional information**
Latest log:
[latest.log](https://github.com/user-attachments/files/15919722/latest.log)

**Comment by DeDiamondPro** [comment]
Well this is new, I think this is most likely a mod conflict, (if possible) could you send the link of the modpack you are using?

**Comment by Anonyku05** [comment]
It's a custom modpack i made over the last months, i can give you a link to all the mods so you can use them directly:
https://mega.nz/folder/ejRAiKbS#FOHZQBZvem_5378YuVkbGA

**Comment by DeDiamondPro** [comment]
I'll look into it tomorrow, I appreciate you giving me the jars but for security reasons I will download them from modrinth/curseforge myself.

**Comment by Anonyku05** [comment]
I was doubting you would say that, that's why i can give you the mods name list directly:

**- additionallanterns-1.1.1a-neoforge-mc1.20.4.jar
- AdvancementPlaques-1.20.4-fabric-1.6.1.jar
- AmbientSounds_FABRIC_v5.3.9_mc1.20.4.jar
- amethystequipment-v2.2.0-fabric-1.20-1.20.4.jar
- appleskin-fabric-mc1.20.3-2.5.1.jar
- architectury-11.1.17-fabric.jar
- Armorful-3.0.1+1.20.4.jar
- AttributeFix-Fabric-1.20.4-24.0.2.jar
- autosmeltenchant-1.3.2.jar
- BadOptimizations-2.1.4-1.20.2-20.4.jar
- BambooEverything-fabric-4.1.0+mc1.20.4.jar
- BarteringStation-v20.4.1-1.20.4-Fabric.jar
- bedrockbreakers-1.6.jar
- better-end-sky-0.2.1+1.20.jar
- betterbeds-1.3.0-1.19.3.jar
- BetterFurnaces-1.20.4-1.0.2-fabric.jar
- BetterSmithingTable-1.1.2-Fabric-1.20.4.jar
- BetterThanMending-fabric-2.0.0.jar
- bettertrims-2.2.3.jar
- blood-moon-1.0.0-Pr2.jar
- blur-3.2.0.jar
- BOMD-1.8.2-1.20.4.jar
- Bookshelf-Fabric-1.20.4-23.0.8.jar
- borderless-mining-1.1.9+1.20.2.jar
- c2me-fabric-mc1.20.4-0.2.0+alpha.11.67.jar
- Camerapture-1.3.1+mc1.20.4.jar
- capes-1.5.3+1.20.2-fabric.jar
- cardinal-components-api-5.4.0.jar
- cavedweller-1.3.0.jar
- cave_dust-1.4.1.jar
- charmofundying-fabric-7.1.2+1.20.4.jar
- cloth-config-13.0.121-fabric.jar
- collective-1.20.4-7.49.jar
- colorfulhearts-fabric-1.20.4-7.1.10.jar
- completeconfig-2.5.3.jar
- configurablemobpotioneffects-1.20.4-3.3.jar
- continuity-3.0.0-beta.5+1.20.2.jar
- copperhopper-0.7.0+1.20.4.jar
- CosmeticArmor-1.20-1.6.0.jar
- craft-enchanted-golden-apple-v.1.0.0.jar
- craft-spawner-v.1.0.0.jar
- CreativeCore_FABRIC_v2.11.26_mc1.20.4.jar
- cryingportals-1.20.4-2.7.jar
- CustomPlayerModels-Fabric-1.20.4-0.6.17a.jar
- cyclepaintings-1.20.4-3.5.jar
- cycletitlescreensplash-1.20.4-1.2.jar
- dark-loading-screen-1.6.14.jar
- Debugify-1.20.4+1.1.jar
- deeperdarker-fabric-1.20.4-1.2.6.jar
- DeleteWorldsToTrash-v20.4.0-1.20.4-Fabric.jar
- DisableCustomWorldsAdvice-5.0.jar
- DistantFriends-fabric-1.20.4-0.7.1.jar
- DistinguishedPotions-v20.4.1-1.20.4-Fabric.jar
- DripSounds-1.19.4-0.3.2.jar
- dwdsb-1.5.1.jar
- DynamicSurroundings-Fabric-1.20.4-0.3.3.jar
- earlyloadingscreen-mc1.20.4-0.1.5-all.jar
- EasyAnvils-v20.4.6-1.20.4-Fabric.jar
- EasyMagic-v20.4.0-1.20.4-Fabric.jar
- EchoChest-v20.4.1-1.20.4-Fabric.jar
- elytratrims-fabric-3.2.0+1.20.4.jar
- emissive-plugin-1.20.4-2.0.4-fabric.jar
- emoji-type-2.2.3+1.20.4-fabric.jar
- EnchantingInfuser-v20.4.1-1.20.4-Fabric.jar
- enchantips-1.2.1.jar
- EnchantmentDescriptions-Fabric-1.20.4-20.0.4.jar
- ender-eyes-1.20.3-1.20.4-3.1.0.jar
- endermanoverhaul-fabric-1.20.4-1.1.8.jar
- EnderZoology-v20.4.3-1.20.4-Fabric.jar
- endportalrecipe-1.20.4-5.2.jar
- EnhancedVisuals_FABRIC_v1.7.1_mc1.20.4.jar
- entityculling-fabric-1.6.6-mc1.20.4.jar
- epileson-fabric-1.0.1+1.20-1.20.4.jar
- explosive-enhancement-1.2.2-1.20.x.jar
- ExtendedDrawers-2.1.1+mc.1.20.4.jar
- extractpoison-1.20.4-3.3.jar
- ExtremeSoundMuffler-3.45-fabric-1.20.4.jar
- fabric-1.20.4-optionsprofiles-1.2.1.jar
- fabric-api-0.97.1+1.20.4.jar
- fabric-experiencebugfix-1.20-2.jar
- fabric-hammers-1.3.0.jar
- fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
- FactoryAPI-1.20.4-2.1.3-fabric.jar
- fallingleaves-1.15.6+1.20.1.jar
- ferritecore-6.0.3-fabric.jar
- firstperson-fabric-2.4.3-mc1.20.4.jar
- fishing_ruler-1.0.2-mc1.20.4.jar
- fluidvoidfading-1.1.5+1.20.4.jar
- FogLooksGoodNow-2.2.0+1.20.4.jar
- forcecrawl-fabric-1.20-1.0.2.jar
- ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
- formations-1.0.2-fabric-mc1.20.4.jar
- formationsnether-1.0.4.jar
- formationsoverworld-1.0.3.jar
- friendsandfoes-fabric-mc1.20.4-2.0.10.jar
- friendsandfoes-flowerymooblooms-fabric-mc1.20.4-2.0.1.jar
- From-The-Fog-1.20.3-1.20.4-v1.9.3-Forge-Fabric.jar
- gamemenuremovegfarb-fabric-mc1.19.4-2.1.2.jar
- geckolib-fabric-1.20.4-4.4.4.jar
- glassbreaker-fabric-1.4.0+1.20.jar
- GlitchCore-fabric-1.20.4-1.0.0.59.jar
- grindstonesharpertools-1.20.4-3.5.jar
- healingcampfire-1.20.4-5.3.jar
- Iceberg-1.20.4-fabric-1.1.18.jar
- IllagerInvasion-v20.4.3-1.20.4-Fabric.jar
- ImmediatelyFast-Fabric-1.2.18+1.20.4.jar
- indium-1.0.31+mc1.20.4.jar
- inventoryhud.fabric.1.20.4-3.4.22.jar
- inventorymanagement-1.5.0+1.20.3.jar
- IronChests-2.0.1.jar
- IronDoorKey-FABRIC-1.20.1-1.1.jar
- ironladders-1.20.4-2.1.51-fabric.jar
- ItemBorders-1.20.2-fabric-1.2.1.jar
- ItemPhysic_FABRIC_v1.7.1_mc1.20.4.jar
- Jade-1.20.4-fabric-13.3.1.jar
- jei-1.20.4-fabric-17.3.0.2.jar
- keepmysoiltilled-1.20.4-2.2.jar
- krypton-0.2.6.jar
- language-reload-1.6.1+1.20.4.jar
- lazydfu-0.1.3.jar
- LeavesBeGone-v20.4.1-1.20.4-Fabric.jar
- LetSleepingDogsLie-1.20.4-Fabric-1.2.0.jar
- LevelTextFix-Fabric-1.20.4-10.0.3.jar
- libIPN-fabric-1.20.3-4.0.2.jar
- lithium-fabric-mc1.20.4-0.12.1.jar
- loadingbackgrounds-1.4.1-fabric-1.20.1.jar
- mcpitanlib-2.2.4-1.20.4-fabric.jar
- mcw-bridges-3.0.0-mc1.20.4fabric.jar
- mcw-doors-1.1.1fabric-mc1.20.4.jar
- mcw-fences-1.1.2-mc1.20.4fabric.jar
- mcw-furniture-3.2.2-mc1.20.4fabric.jar
- mcw-lights-1.1.0-mc1.20.4fabric.jar
- mcw-paintings-1.0.5-1.20.4fabric.jar
- mcw-paths-1.0.5-1.20.4fabric.jar
- mcw-roofs-2.3.0-mc1.20.4fabric.jar
- mcw-trapdoors-1.1.3-mc1.20.4forge.jar
- mcw-windows-2.2.1-mc1.20.4fabric.jar
- Measurements-fabric-1.20.4-2.2.0.jar
- merenc-fabric-1.20.x-v3.2.jar
- mes-1.3.1-1.20-fabric.jar
- MineMath-2.0.0-1.20.4.jar
- mineralchance-1.20.4-3.6.jar
- mo-variants-7.5.1J.jar
- MobCaptains-v3.2.1.jar
- MobCatcher-Fabric-1.20.4-1.4.8.jar
- Model-Gap-Fix-Mod-Fabric-1.20.4.jar
- modernfix-fabric-5.17.0+mc1.20.4.jar
- modmenu-9.2.0.jar
- MoreChestVariants-1.5.5+1.20.4-Fabric.jar
- moremcmeta-1.20.4-4.4.7-fabric.jar
- MoT v1.1 - fabric 1.20.4.jar
- MouseTweaks-fabric-mc1.20-2.26.jar
- mru-0.4.2+1.20.4.jar
- music_control-1.8+1.20.4.jar
- music_player-fabric-1.20.4-2.7.1.257.jar
- MutantMonsters-v20.4.1-1.20.4-Fabric.jar
- netherweather-1.0.jar
- no-resource-pack-warnings-1.3.0.jar
- no-telemetry-1.8.0.jar
- no-trial-chambers-1.2.jar
- noisium-fabric-2.0.3+mc1.20.2-1.20.4.jar
- notenoughanimations-fabric-1.7.4-mc1.20.4.jar
- ObsidianUI-fabric-0.2.4+mc1.20.4.jar
- OverpoweredMending-1.20.4-1.20.4.1.jar
- owo-lib-0.12.5+1.20.3.jar
- packetfixer-fabric-1.4.1-1.20.2-to-1.20.4.jar
- packrule-menus-1.2.2+1.20.1.jar
- Patchouli-1.20.4-85-FABRIC.jar
- PickUpNotifier-v20.4.2-1.20.4-Fabric.jar
- placeableblazerods-1.20.4-3.4.jar
- Potion-Blender-1.20.4-FABRIC-2.0.0.jar
- potioncraft-0.3.2+1.20.4.jar
- PresenceFootsteps-1.9.4+1.20.4.jar
- Prism-1.20.4-fabric-1.0.6.jar
- puffish_attributes-0.3.0-1.20.4-fabric.jar
- puffish_skills-0.12.2-1.20.4-fabric.jar
- purpurclient-1.20.4-31.jar
- purpurpacks-axe-effective-skulls-1.5.jar
- PuzzlesLib-v20.4.42-1.20.4-Fabric.jar
- Quad-1.2.3+1.20.4-Fabric.jar
- realisticsleep-1.10.2+mc1.20.3-1.20.4.jar
- reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar
- reimaginedmenus-2.0.0-1.20.4.jar
- ReinforcedObsidian-1.20.4-0.1.jar
- replaymod-1.20.4-2.6.15.jar
- resourcefulconfig-fabric-1.20.4-2.4.7.jar
- resourcefullib-fabric-1.20.4-2.4.10.jar
- resource_explorer_fabric_1.20.4-1.1.jar
- Resourcify (1.20.2-1.20.4-fabric)-1.4.0.jar
- rfdeepslateminer-1.0.0.jar
- RyoamicLights-fabric-0.2.5+mc1.20.4.jar
- scorpions-fabric-1.20.1-1.3.2.jar
- screenfx-1.4.1+1.20.4.jar
- screenshot-to-clipboard-1.0.9-fabric.jar
- screenshot_viewer-1.3.1-fabric-mc1.20.4.jar
- sculk-expansion-1.3.2.jar
- SereneSeasons-fabric-1.20.4-9.3.0.18.jar
- shulkerboxtooltip-fabric-4.1.0+1.20.4.jar
- shutupdeadentities-mc1.20.3+1.1.jar
- smallernetherportals-1.20.4-3.6.jar
- smart-villagers-follow-emeralds-1.0.0.jar
- smoke-suppression-1.0.20+MC1.20.2-1.20.6.jar
- SnowUnderTrees-2.3.0+1.20.4.jar
- sodium-extra-0.5.4+mc1.20.4-build.116.jar
- sodium-fabric-0.5.8+mc1.20.4.jar
- sodium-shadowy-path-blocks-3.3.0.jar
- sound-physics-remastered-fabric-1.20.4-1.4.2.jar
- spawnermod-1.20.4-1.2.5+Fabric.jar
- SpikySpikes-v20.4.1-1.20.4-Fabric.jar
- spyglass-improvements-1.5.1+mc1.20.2+fabric.jar
- spyglass_astronomy-1.0.10-mc1.20.2.jar
- stamina-meter-4.jar
- starlight-1.1.3+fabric.f5dcd1a.jar
- stendhal-1.4.1-1.20.2.jar
- supermartijn642corelib-1.1.17a-fabric-mc1.20.4.jar
- sushimod-v1.1.0-fabric-1.20-1.20.4.jar
- threadtweak-fabric-1.20.4-0.1.2.jar
- time-and-wind-ct-1.4.8+1.20.2-1.20.4.jar
- TinySkeletons-v20.4.1-1.20.4-Fabric.jar
- tooltipfix-1.1.1-1.20.jar
- toomanypaintings-1.0.1-1.20-fabric.jar
- ToughAsNails-fabric-1.20.4-9.2.0.169.jar
- TradingPost-v20.4.2-1.20.4-Fabric.jar
- trashcans-1.0.18-fabric-mc1.20.jar
- travelersbackpack-fabric-1.20.4-9.4.4.jar
- trinkets-3.8.1.jar
- tru.e-ending-v1.1.0c.jar
- TrueDarknessFork-1.0.2-1.20.x.jar
- unlitcampfire-fabric-1.20.4-2.3.0.1.jar
- u_team_core-fabric-1.20.4-5.3.0.300.jar
- veinmining-fabric-3.1.1+1.20.4.jar
- visuality-0.7.4+1.20.4.jar
- VisualWorkbench-v20.4.2-1.20.4-Fabric.jar
- wakes-0.2.4.jar
- wardenhorn-1.7-fabric-mc1.20.1.jar
- warriorrage-fabric-1.20.4-1.4.0.jar
- WhatTheBucket-Fabric-1.20.4-14.0.2.jar
- wither-cage-fix-1.0.22+MC1.20-1.21.jar
- woof-4.0.2+1.20.4.jar
- worldplaytime-1.2.1-1.20.4-FABRIC.jar
- wraith-waystones-3.3.2+mc1.20.4.jar
- yet-another-config-lib-fabric-3.3.1+1.20.4.jar
- zombiehorsespawn-1.20.4-4.8.jar**

**Comment by DeDiamondPro** [comment]
Unfortunately I am not able to reproduce the issue.

Could you first see if you have this issue with only Resourcify. 
If that fixes it could you put half of your mods back in.
if the issue occurs again, half your current mods folder again and see if the issue still happens
if not, try the other half and repeat this process until the mod that is causing issues has been found

I know with this many mods it will probably take a while but unfortunately since I can't seem to reproduce this issue I cannot find the conflicting mod myself.

**Comment by Anonyku05** [comment]
Little update but this issue seems super weird, i was able to reproduce it but didn't knew wich mod was responsible, now i removes like 50 mods and the issue was gone, i put them back alone and the issue was still gone, i put back the rest of my mods and now even with all of my modpack the issue is gone again.

It's nearly like it's with a specific configuration but can't figure out wich one

**Comment by GrostK** [comment]
I had the same bug, but to replicate that:
- open the mod menu;
- exit the mod menu;
- go to the options, resource packs, updates;
- close the updates.

In singleplayer after that you will end up on game menu, not on start menu, the same goes for multiplayer.
But i think there is another mod, that causes to go to the main screen instead of game menu.

The list of mods here:
	- appleskin 3.0.5+mc1.21
	- architectury 13.0.6
	- balm-fabric 21.0.18
	- betterf3 11.0.1
	- betterpingdisplay 1.1.1
	- betterstats 3.13.1+fabric-1.21
	- blur 4.1.0
	- bridgingmod 2.4.0+1.21
	- camerautils 1.21.1-1.0.15
	- capes 1.5.4+1.21
	- cat_jam 1.2.3
	- chat_heads 0.12.10
	- cicada 0.8.3+1.21-and-above
	- cloth-config 15.0.130
	- clumps 19.0.0.1
	- collective 7.84
	- continuity 3.0.0-beta.5+1.21
	- controlling 19.0.1
	- craftingtweaks 21.1.2
	- craftpresence 2.5.0
	- cullleaves 3.4.0
	- detailab 2.6.3+1.21.1-fabric
	- do_a_barrel_roll 3.6.2+1.21
	- durabilitytooltip 1.1.5
	- dynamic_fps 3.6.3
	- enhanced_attack_indicator 1.0.4+1.21
	- entity-desync-viewer 1.0.0
	- entity_model_features 2.2
	- entity_sound_features 0.4
	- entity_texture_features 6.2
	- entityculling 1.6.7
	- essential-container 1.0.0
	- essential-dependencies 0
	- euphoria_patcher 0.3.4-fabric
	- explosiveenhancement 1.2.3-1.21.0
	- fabric-api 0.102.1+1.21.1
	- fabric-language-kotlin 1.12.1+kotlin.2.0.20
	- fabricloader 0.16.2
	- fabricskyboxes 0.7.4+mc1.21
	- falling-block-particles 1.0.2
	- fastquit 3.0.0+1.20.6
	- ferritecore 7.0.0
	- fog 1.3.1-1.21
	- fsb-interop 1.4.0+mc1.21-build.54
	- holdthatchunk 2.1.0
	- immediatelyfast 1.2.20+1.21.1
	- inventoryprofilesnext 2.0.4
	- iris 1.8.0-beta.2+mc1.21.1
	- jade 15.2.1+fabric
	- java 21
	- ksyxis 1.3.2
	- languagereload 1.6.1+1.21
	- libipn 6.0.2
	- litematica 0.19.50
	- lithium 0.13.0
	- make_bubbles_pop 0.3.0-fabric
	- malilib 0.21.0
	- midnightlib 1.5.8
	- minecraft 1.21.1
	- minihud 0.32.50
	- modmenu 11.0.1
	- morechathistory 1.3.1
	- mousetweaks 2.26
	- movement-in-gui 1.0.2
	- mru 1.0.2+1.21+fabric
	- namepain 1.5.3
	- nochatreports 1.21-v2.8.0
	- notenoughanimations 1.7.5
	- noxesium 2.2.0+8a453d2
	- optigui 2.3.0-beta.2+1.21
	- owo 0.12.10+1.21
	- packetfixer 1.4.1
	- particlerain 2.1.4
	- particular 1.1.1+1.21
	- peek 1.21.1-1.3.5
	- placeholder-api 2.4.1+1.21
	- reeses-sodium-options 1.8.0-beta.2+mc1.21.1
	- resourcify 1.4.0
	- roughlyenoughitems 16.0.754
	- rrls 5.0.7+mc1.21-fabric
	- searchables 1.0.1
	- serverpackpriority 1.0.2-1.21
	- shulkerboxtooltip 5.1.0+1.21.1
	- skinlayers3d 1.6.7
	- sodium 0.6.0-beta.1+mc1.21
	- sodium-extra 0.6.0-beta.1+mc1.21.1
	- sound_physics_remastered 1.21.1-1.4.6
	- sounds 2.0.4+1.21+fabric
	- spyglass_astronomy 1.0.13-mc1.21+
	- supermartijn642configlib 1.1.8
	- tcdcommons 3.12.3+fabric-1.21
	- tia 1.2.1
	- tweakeroo 0.21.50
	- unilib 1.0.2
	- vcinteraction 1.21.1-1.0.8
	- visuality 0.7.7+1.21
	- visualoverhaul 5.2.1
	- vmp 0.2.0+beta.7.167+1.21.1
	- voicechat 1.21.1-2.5.20
	- wakes 0.2.2-1.21
	- xaerominimap 24.3.0
	- xaeroworldmap 1.39.0

**Comment by DeDiamondPro** [comment]
Hi, thank you for providing some more information. If i do the steps you provided it opens the mod menu menu when I close the update GUI, not the main menu. I am hoping these 2 issues are caused by the same issue so fixing one should fix the other. I will start working on a fix!

**Comment by DeDiamondPro** [comment]
@Anonyku05 @GrostK I have implemented a fix, if you have time could you test if it also fixes your exact issue? Build is here: https://github.com/DeDiamondPro/Resourcify/actions/runs/10558411894/artifacts/1854101722 (built by github actions), jar file for all supported mc versions are in the zip. If this issue still occurs with that version, feel free to reopen this issue.

**Comment by Anonyku05** [comment]
The bug is now fixed, tried the steps and nothing bad happened, thank you !

**Comment by DeDiamondPro** [comment]
A fix for this has been released in 1.4.1
