### ISSUE TITLE
Data pack selection screen also affected

### ISSUE THREAD

**Issue by Felix14-v2** [DeDiamondPro/Resourcify#4]
I guess this button shouldn't be there... 
![image](https://github.com/DeDiamondPro/Resourcify/assets/75726196/2cdea6d7-c5ad-40a2-8894-c33105aa8d7a)
Or is this a hint at datapack support? 👀

**Comment by Felix14-v2** [comment]
By the way, while we're talking about this, how about making the browser open button more seamless? I mean, make it more like a vanilla UI element. Something like that:
![image](https://github.com/DeDiamondPro/Resourcify/assets/75726196/97b8a16c-13a2-4f66-94ac-ec93ee87617a)

This would also solve the [compatibility issue](https://github.com/enjarai/recursive-resources/issues/28) with Recoursive Resources.

**Comment by DeDiamondPro** [comment]
> I guess this button shouldn't be there... ![image](https://user-images.githubusercontent.com/75726196/243229817-2cdea6d7-c5ad-40a2-8894-c33105aa8d7a.png) Or is this a hint at datapack support? eyes

Ah fun, could you please tell me what Minecraft version that is so I can debug it more easily

**Comment by DeDiamondPro** [comment]
> By the way, while we're talking about this, how about making the browser open button more seamless? I mean, make it more like a vanilla UI element. Something like that: ![image](https://user-images.githubusercontent.com/75726196/243232903-78b69363-75f1-4159-98b8-5fa77c9855e0.png)
> 
> This would also solve the [compatibility issue](https://github.com/enjarai/recursive-resources/issues/28) with Recursive Resources.

I'll see, main reason I did it like this is so if I create a feature that requires an extra button, its easy to just add it next to it

**Comment by Felix14-v2** [comment]
> Ah fun, could you please tell me what Minecraft version that is so I can debug it more easily

Oh, sorry for missing technical info.

- Minecraft 1.19.4
- Fabric Loader 0.14.19
- Fabric API 0.80.0
- Resourcify 1.0.0
- A bunch of other mods, but I don't think this is important in this case
