### ISSUE TITLE
Resource / Shader Pack Folders

### ISSUE THREAD

**Issue by Oxeus** [DeDiamondPro/Resourcify#41]
**Is your feature request related to a problem? Please describe.**
No Current Issues.

**Describe the solution you'd like**
If applicable and it seems in line with this mod would it be possible to add folder support or the ability to organize in folders so if folders are detected they act as clickable links that open a new view of the packs in the folder,

**Additional context**
N/A

**Comment by DeDiamondPro** [comment]
You mean something like [Recursive Resources](https://modrinth.com/mod/recursiveresources)? If so it is out of scope for Resourcify.

**Comment by Oxeus** [comment]
All good then, thought it would be a nice feature.
