### ISSUE TITLE
datapacks won't install

### ISSUE THREAD

**Issue by samve000** [DeDiamondPro/Resourcify#43]
**Technical Information**
Resourcify version: 1.4.0
Minecraft version: 1.20.1
Other mods (if relevant):

**Describe the bug**
When I create a new world and try to install a datapack it says "installed", but when I go back to select datapack menu, the datapack isn't there.

**Expected behavior**
The datapack to show up so I can enable it

**Steps to reproduce**
Install Resourcify
Install a Towers of The Wild Reworked datapack

**Additional information**

ARRP register - before user
ARRP register - before user
Found non-pack entry 'C:\Users\samve\AppData\Local\Temp\mcworld-14736527821437624789\dungeons-and-taverns-3.0.3.f.jar', ignoring
Found non-pack entry 'C:\Users\samve\AppData\Local\Temp\mcworld-14736527821437624789\dynamiclights-v1.8.3-mc1.17x-1.21x-mod.jar', ignoring
Found non-pack entry 'C:\Users\samve\AppData\Local\Temp\mcworld-14736527821437624789\Loyal Items 1.0.2.jar', ignoring
Found non-pack entry 'C:\Users\samve\AppData\Local\Temp\mcworld-14736527821437624789\RPGOrigins-1.4.2.jar', ignoring
Missing metadata in pack file/Towers_Of_The_Wild_Reworked_v4.2.2_Fabric_Waystones.zip

**Comment by DeDiamondPro** [comment]
Hi, some datapacks are bundled as mods (that’s why you see the file name ends with .jar), you have to make sure you install the datapack version and not the mod folder, you can see this by checking the loader, if it says Minecraft it is a datapack, if it says fabric/forge it is a mod. 

It is possible that the latest version button would install the jar version if I forgot to reimplement that check when adding curseforge support, I will look into that.

**Comment by samve000** [comment]
The thing is that sometimes I want to install the datapack version and not the mod version in cases that the mod version doesn't work.

**Comment by DeDiamondPro** [comment]
A fix for this has been released in 1.4.1
