### ISSUE TITLE
Release date translate problem

### ISSUE THREAD

**Issue by xMikux** [DeDiamondPro/Resourcify#47]
**Is your feature request related to a problem? Please describe.**
We are translating the mod into Traditional Chinese and noticed that the translation date is displayed with English short month names. This format seems unusual in Chinese, where dates are typically presented in formats such as 2024/08/12 or 2024年08月12號. Is there a way to use numerical dates for months instead of the English short month names?

Thanks!

![Screenshot from 2024-08-12 15-04-21](https://github.com/user-attachments/assets/558ea480-2b5d-4cc4-94a3-e10ad93ee888)

**Comment by DeDiamondPro** [comment]
Hi, translations use standard Java string formatting to replace variables, meaning you can change the format of the date, specifically for the language you are translating to! To do this replace the %t things in the string with what you need, see https://www.novixys.com/blog/java-string-format-examples/#31_Date_and_Time_Formatting for more info.

**Comment by xMikux** [comment]
![image](https://github.com/user-attachments/assets/522e12c2-ddb9-482c-865c-935bb71bf2e8)
Thanks! It works now. 
I will contribute the translate later.
