### ISSUE TITLE
[Crash] Crash on expanding reduced list

### ISSUE THREAD

**Issue by TQCnoARosto** [DeDiamondPro/Resourcify#49]
**Technical Information**
Resourcify version: 1.4.0
Minecraft version: 1.21

**Describe the bug**
Crash on expanding reduced list while browsing resource packs
![image](https://github.com/user-attachments/assets/e45eacb1-087d-460e-b244-58c7b2b4934b)

Crash report: https://pastebin.com/sVQdQ5jU

**Comment by DeDiamondPro** [comment]
A fix for this has been released in 1.4.1
