### ISSUE TITLE
Version 1.5.0 is incompatible with 1.21

### ISSUE THREAD

**Issue by tunaflsh** [DeDiamondPro/Resourcify#53]
**Technical Information**
Resourcify version: 1.5.0
Minecraft version: 1.21

**Comment by DeDiamondPro** [comment]
I’ll look into this later today

**Comment by DeDiamondPro** [comment]
I have released a fix for this in 1.5.0.1, this was a stupid mistake by me causing some versions to be incorrectly marked in the fabric.mod.json file. I have updated the affected versions on modrinth and curseforge to remove the mc versions they arnen't compatible with and I have pushed an update fixing the issue.
