### ISSUE TITLE
Can't seem to download resource packs from a lower minecraft version

### ISSUE THREAD

**Issue by MCRusher** [DeDiamondPro/Resourcify#6]
When I change version even to 1.20 from my game version of 1.20.1, The install button is missing for 1.20 packs.

This feels strange since resource packs are a lot less version-picky than mods, and many of the resource packs I use in 1.20.X are still 1.19.X but work perfectly still.

I didn't want to label this as a bug since this might be intentional, so I guess this could be more like a feature request?

This means most of the time I have to open modrinth anyways to download the resource pack.

---

For up-to-date packs though, this mod is great and convenient, so thanks for making it and maintaining it.

I hope this didn't sound like a complaint.

**Comment by DeDiamondPro** [comment]
This is indeed intended behavior, Resourcify will only show the install button in the top left if it finds a version that is a match to your mc version

However you can still download a resource pack from an older mc version right from resourcify, to do this you have to go to the versions page of your pack and then click the install button on the version you want
